#!/bin/sh
# Wraps app.html (the Artifact source, which must not carry its own document
# tags) into a standalone index.html for GitHub Pages. The wrapper mirrors what
# the Artifact publisher does, so both copies behave identically.
# Run after editing app.html.
set -e
dir=$(dirname "$0")
{
  printf '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
  printf '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
  printf '</head>\n<body>\n'
  printf '<!-- Generated by build.sh from app.html - edit app.html, not this file. -->\n'
  cat "$dir/app.html"
  printf '\n</body>\n</html>\n'
} > "$dir/index.html.tmp"
mv "$dir/index.html.tmp" "$dir/index.html"
echo "built $dir/index.html"
